# Generated by Django 4.1.4 on 2023-01-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=300)),
                ("comment", models.TextField()),
                ("slug", models.CharField(max_length=300)),
                ("star", models.IntegerField()),
                ("date", models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="label",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("hot", "hot"),
                    ("sale", "sale"),
                    ("", "default"),
                ],
                max_length=20,
            ),
        ),
    ]
